language: php
sudo: false
php:
- 7.1
- 7.2
- 7.3
before_install:
- composer install
# Install Swagger-generated dependencies separately,
# but don't change directories in the main process
- (cd swagger/SwaggerClient-php && composer install)
script:
- vendor/bin/phpunit
# Test Swagger-generated code separately (using its own older version of PHPUnit)
- swagger/SwaggerClient-php/vendor/bin/phpunit --configuration swagger/SwaggerClient-php/phpunit.xml.dist

cache:
  directories:
  - $HOME/.cache/composer
