<?php
/**
 * AISearchResultFeedbackLabelsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * GearLab Tools
 *
 * Authoritative documentation for querying the GearLab Tools API. Client SDKs are generated from this API specification.
 *
 * OpenAPI spec version: v4.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.46
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AISearchResultFeedbackLabelsTest Class Doc Comment
 *
 * @category    Class
 * @description AISearchResultFeedbackLabels
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AISearchResultFeedbackLabelsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AISearchResultFeedbackLabels"
     */
    public function testAISearchResultFeedbackLabels()
    {
    }

    /**
     * Test attribute "label_text"
     */
    public function testPropertyLabelText()
    {
    }

    /**
     * Test attribute "sentiment_name"
     */
    public function testPropertySentimentName()
    {
    }

    /**
     * Test attribute "label_id"
     */
    public function testPropertyLabelId()
    {
    }
}
