<?php
/**
 * SearchResponseResSetTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * GearLab Tools
 *
 * Authoritative documentation for querying the GearLab Tools API. Client SDKs are generated from this API specification.
 *
 * OpenAPI spec version: v3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.43
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SearchResponseResSetTest Class Doc Comment
 *
 * @category    Class
 * @description SearchResponseResSet
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SearchResponseResSetTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SearchResponseResSet"
     */
    public function testSearchResponseResSet()
    {
    }

    /**
     * Test attribute "results"
     */
    public function testPropertyResults()
    {
    }

    /**
     * Test attribute "recommendations"
     */
    public function testPropertyRecommendations()
    {
    }

    /**
     * Test attribute "res_offset"
     */
    public function testPropertyResOffset()
    {
    }

    /**
     * Test attribute "res_start"
     */
    public function testPropertyResStart()
    {
    }

    /**
     * Test attribute "res_end"
     */
    public function testPropertyResEnd()
    {
    }

    /**
     * Test attribute "res_count"
     */
    public function testPropertyResCount()
    {
    }

    /**
     * Test attribute "total"
     */
    public function testPropertyTotal()
    {
    }

    /**
     * Test attribute "literal_query"
     */
    public function testPropertyLiteralQuery()
    {
    }

    /**
     * Test attribute "original_query_phrase"
     */
    public function testPropertyOriginalQueryPhrase()
    {
    }

    /**
     * Test attribute "suggestion_superseded_query"
     */
    public function testPropertySuggestionSupersededQuery()
    {
    }

    /**
     * Test attribute "superseding_suggestion"
     */
    public function testPropertySupersedingSuggestion()
    {
    }

    /**
     * Test attribute "curated_results_enabled"
     */
    public function testPropertyCuratedResultsEnabled()
    {
    }

    /**
     * Test attribute "curated_results_version"
     */
    public function testPropertyCuratedResultsVersion()
    {
    }

    /**
     * Test attribute "curated_results"
     */
    public function testPropertyCuratedResults()
    {
    }
}
